libpcap:
  - 1.9 
pin_run_as_build:
  libpcap:
    max_pin: x.x
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.11                  # [osx]
macos_min_version:         # [osx]
  - 10.11                  # [osx]
