{% set name = "mongo-tools" %}
{% set version = "4.2.5" %}
{% set checkout_dir = "src/github.com/mongodb/mongo-tools" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/mongodb/{{ name }}.git
    git_rev: r{{ version }}
    folder: {{ checkout_dir }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cgo') }}
    - {{ compiler('c') }}
    - git
    - make
  host:
    - libpcap
    - openssl
  run:
    - libpcap

test:
  commands:
    # Binary Import and Export Tools
    - bsondump --help
    - mongodump --help
    - mongorestore --help

    # Data Import and Export Tools
    - mongoimport --help
    - mongoexport --help

    # Diagnostic Tools
    - mongostat --help
    - mongotop --help
    - if [ $(nproc) -ge 2 ]; then  mongoreplay --version; fi
    # - mongoldap is not available in the OpenSource repo

    # GridFS
    - mongofiles --help

about:
  home: https://www.mongodb.com
  license: Apache-2.0
  license_file: {{ checkout_dir }}/LICENSE.md
  summary: Tools for managing and monitoring MongoDB clusters
  dev_url: https://github.com/mongodb/mongo-tools
  doc_url: https://docs.mongodb.com/master/reference/program/

extra:
  recipe-maintainers:
    - sodre
    - nehaljwani
