{% set version = "100.12.1" %}

package:
  name: mongo-tools
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-tools/archive/{{ version }}.tar.gz
  sha256: 611578ab2fb2c0d65972205f416b458082de9c7b61f1836b850622ed25e4ad10

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    # Binary Import and Export Tools
    - bsondump --help
    - mongodump --help
    - mongorestore --help

    # Data Import and Export Tools
    - mongoimport --help
    - mongoexport --help

    # Diagnostic Tools
    - mongostat --help
    - mongotop --help
    # - mongoldap is not available in the OpenSource repo

    # GridFS
    - mongofiles --help

about:
  home: https://www.mongodb.com
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - license-files_bsondump/
    - license-files_mongodump/
    - license-files_mongorestore/
    - license-files_mongoimport/
    - license-files_mongoexport/
    - license-files_mongostat/
    - license-files_mongotop/
    - license-files_mongofiles/
  summary: Tools for managing and monitoring MongoDB clusters
  dev_url: https://github.com/mongodb/mongo-tools
  doc_url: https://docs.mongodb.com/master/reference/program/

extra:
  recipe-maintainers:
    - sodre
    - nehaljwani
