{% set name = "mongo-tools" %}
{% set version = "3.6.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/mongodb/{{ name }}.git
    git_rev: r{{ version }}

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - git
    - make
    - sed

test:
  commands:
    # Binary Import and Export Tools
    - bsondump --help
    - mongodump --help
    - mongorestore --help

    # Data Import and Export Tools
    - mongoimport --help
    - mongoexport --help

    # Diagnostic Tools
    - mongostat --help
    - mongotop --help
    # - mongoreplay --help  # mongoreplay needs libpcap and CGO_ENABLED=1 to work
    # - mongoldap is not available in the OS repo
    
    # GridFS
    - mongofiles --help

about:
  home: https://www.mongodb.com
  license: Apache 2.0
  summary: Tools for managing and monitoring MongoDB clusters
  dev_url: https://github.com/mongodb/mongo-tools
  doc_url: https://docs.mongodb.com/master/reference/program/

extra:
  recipe-maintainers:
    - sodre
    - nehaljwani
