{% set name = "mongo-tools" %}
{% set version = "100.2.0" %}
{% set gopath = "gopath/src/github.com/mongodb/mongo-tools" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ gopath }}
    url: https://github.com/mongodb/{{ name }}/archive/{{ version }}.tar.gz
    sha256: a776ea5af5091d558ab0151302699783cb03e10ef026ef4b389a2f8b431cb127
    patches:
      - 0001-Use-GOROOT-GOPATH-CGO_FLAGS-GOBIN-GOEXE.patch

build:
  number: 0
  script:
    - cd {{ gopath }}
    - ./build.sh ssl                                                       # [unix]
    - bash -c 'PREFIX=$LIBRARY_PREFIX PATH=$PATH:$LIBRARY_BIN ./build.sh'  # [win]

requirements:
  build:
    - {{ compiler('cgo') }} 1.13
    - {{ compiler('c') }}
  host:
    - openssl  # [unix]
    - m2-bash  # [win]
    - m2-base  # [win]

test:
  commands:
    # Binary Import and Export Tools
    - bsondump --help
    - mongodump --help
    - mongorestore --help

    # Data Import and Export Tools
    - mongoimport --help
    - mongoexport --help

    # Diagnostic Tools
    - mongostat --help
    - mongotop --help
    # - mongoldap is not available in the OpenSource repo

    # GridFS
    - mongofiles --help

about:
  home: https://www.mongodb.com
  license: Apache-2.0
  license_file: {{ gopath }}/LICENSE.md
  summary: Tools for managing and monitoring MongoDB clusters
  dev_url: https://github.com/mongodb/mongo-tools
  doc_url: https://docs.mongodb.com/master/reference/program/

extra:
  recipe-maintainers:
    - sodre
    - nehaljwani
